-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 21, 2024 at 01:08 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bpbooks`
--

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `productID` int(10) NOT NULL,
  `title` text NOT NULL,
  `oldPrice` int(11) NOT NULL,
  `newPrice` int(11) NOT NULL,
  `img1` varchar(50) NOT NULL,
  `img2` varchar(50) NOT NULL,
  `img3` varchar(50) NOT NULL,
  `img4` varchar(50) NOT NULL,
  `rating` float NOT NULL,
  `description` text NOT NULL,
  `nxb` varchar(50) NOT NULL,
  `author` varchar(50) NOT NULL,
  `age` int(11) NOT NULL,
  `theLoai` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`productID`, `title`, `oldPrice`, `newPrice`, `img1`, `img2`, `img3`, `img4`, `rating`, `description`, `nxb`, `author`, `age`, `theLoai`) VALUES
(1, 'Thanh Gươm Diệt Quỷ - Kimetsu No Yaiba - Tập 20 - Trái Tim Kiên Định Dẫn Lối', 25000, 24000, 'images/product/kny20_1.png', 'images/product/kny20_2.png', 'images/product/kny20_3.png', 'images/product/kny20_4.png', 4, '<p>Thanh Gươm Diệt Quỷ - Kimetsu No Yaiba - Tập 20: Trái Tim Kiên Định Dẫn Lối</p>\r\n<p>Nham trụ Himejima và Phong trụ Shinazugawa cùng đối đầu với Thượng huyền nhất. Trận chiến càng lúc càng khốc liệt, hai người đều đã xuất hiện vết bớt trên cơ thể. Nhưng dù đã cùng phối hợp tấn công, họ vẫn bị áp đảo trước sức mạnh khủng khiếp của Thượng huyền nhất. Genya đã hồi phục nhờ hấp thu được một phần của Thượng huyền nhất, nhưng liệu kết quả trận chiến sẽ ra sao…!?</p>\r\n<p>“Thanh gươm diệt quỷ” đang bước vào hồi gay cấn nhất!! Xin mời các bạn độc giả tiếp tục theo dõi Vol.20 nhé!!</p>', 'Nhà Xuất Bản Kim Đồng', 'Koyoharu Gotouge', 16, 'Hành_động'),
(2, 'Thanh Gươm Diệt Quỷ - Kimetsu No Yaiba - Tập 8 - Sức Mạnh Của Thượng Huyền - Sức Mạnh Của Trụ Cột', 25000, 24000, 'images/product/kny8_1.png', 'images/product/kny8_2.png', 'images/product/kny8_3.png', 'images/product/kny8_4.png', 5, '<p>Thanh Gươm Diệt Quỷ - Kimetsu No Yaiba - Tập 8: Sức Mạnh Của Thượng Huyền - Sức Mạnh Của Trụ Cột</p>\r\n<p>Tanjiro đã sử dụng Hỏa thần thần lạc - Bích La Thiên để chiến đấu với quỷ giấc mơ Enmu. Liệu trận chiến đã đến hồi kết!? Và bản chất của thứ xuất hiện trên cơ thể Tanjiro là gì? Cuối cùng, Viêm trụ Rengoku Kyojuro cũng đã hành động. Trước những lời từ một người mạnh, thứ mà Tanjiro thấy là….!?</p>\r\n<p>“Xin chào, lại là Gotouge đây! Mọi người có khỏe không? Sức khỏe không thể mua được bằng tiền, nên tôi cầu mong mọi người đều mạnh khỏe. Cảm ơn các bạn đã gửi tới tôi thật nhiều lời động viên, trà bánh và đồ handmade nữa! Ngày nào tôi cũng háo hức đến mức chảy cả máu cam kìa. Mỗi khi bị chảy máu cam tôi đều nhét giấy và đeo mặt nạ kín mít nên không sao đâu, các bạn đừng lo!” (KOYOHARU GOTOUGE)</p>', 'Nhà Xuất Bản Kim Đồng', 'Koyoharu Gotouge', 16, 'Hành_động'),
(3, 'My Hero Academia - Học Viện Siêu Anh Hùng - Tập 26 - Trời Cao Xanh Thẳm', 25000, 24000, 'images/product/mha26_1.png', 'images/product/mha26_2.png', 'images/product/mha26_3.png', 'images/product/mha26_4.png', 4, '<p>My Hero Academia - Học Viện Siêu Anh Hùng - Tập 26 - Trời Cao Xanh Thẳm</p>\r\n<p>Sau khi nhận được thông tin bí mật từ Hawks và bộ an ninh công cộng, ta mới phát hiện… hóa ra kì thực tập lần này là để biến các học sinh thành chiến lực hỗ trợ cho cuộc chiến của các Villain sắp tới…!?</p>\r\n<p>Được thôi, Siêu Anh hùng hạng nhất đương nhiệm này sẽ huấn luyện cả 3 đứa ra ngô ra khoai nhé!</p>\r\n<p>“Plus Ultra”!!</p>', 'Nhà Xuất Bản Kim Đồng', 'Ruyuha Kyouka', 11, 'Hành_động'),
(4, 'My Hero Academia - Học Viện Siêu Anh Hùng - Tập 21 - Lí Do Người Anh Hùng Trụ Vững', 25000, 24000, 'images/product/mha21_1.png', 'images/product/mha21_2.png', 'images/product/mha21_3.png', 'images/product/mha21_4.png', 4, '<p>My Hero Academia - Học Viện Siêu Anh Hùng - Tập 21: Lí Do Người Anh Hùng Trụ Vững (Tái Bản 2022)</p>\r\n<p>Nguy rồi! Lũ Nomu lại làm loạn trong thành phố! Ba của Todoroki đang dồn toàn bộ sức lực ngăn cản chúng! Còn Todoroki cũng đang rất sốt sắng! Nhưng tớ nghĩ là mọi thứ sẽ ổn thôi! Bởi Endeavor là Siêu anh hùng số 1 mà! Tụi tớ luôn tin tưởng và ủng hộ ông ấy! </p>\r\n<p>“Plus Ultra”!!</p>', 'Nhà Xuất Bản Kim Đồng', 'Ruyuha Kyouka', 11, 'Hành_động'),
(5, 'Dragon Ball - 7 Viên Ngọc Rồng - Tập 3 - Đại Hội Võ Thuật Khởi Tranh!', 25000, 24000, 'images/product/drb3_1.png', 'images/product/drb3_2.png', 'images/product/drb3_3.png', 'images/product/drb3_4.png', 4, '<p>Dragon Ball là bộ truyện tranh thiếu niên dài kì nổi tiếng của tác giả Toriyama Akira trên tuần san Weely Shonen Jump. Bộ truyện ra đời năm 1984 và kết thúc vào năm 1995 với tổng cộng 519 chương, chia thành 42 tập truyện rời do NXB Shueisha phát hành.</p>\r\n<p>Bộ truyện kể về một cậu bé đuôi khỉ tên là Son Goku sống một mình trong chốn rừng sâu. Cậu rất coi trọng viên ngọc kỉ vật quý giá ông nội để lại trước khi mất.</p>\r\n<p>Một ngày nọ, cậu vô tình gặp một cô gái kì lạ tên là Bulma đang trên đường tìm kiếm 7 viên ngọc rồng truyền thuyết. Bulma chỉ cho Son Goku thấy rằng, viên ngọc gia bảo của cậu chính là viên ngọc 4 sao, 1 trong 7 viên ngọc rồng mà cô đang tìm kiếm, còn rủ Son Goku tham gia phiêu lưu cùng với mình nữa. Chẳng mảy may suy nghĩ, Goku vui vẻ nhận lời và kể từ đó, cậu nhóc chính thức bước vào một hành trình vĩ đại, không đơn giản chỉ là tìm ngọc rồng nữa, mà là bảo vệ chúng khỏi những kẻ xấu xa mang dã tâm lớn như: Tập đoàn Red Ribbon, Đại Ma Vương Piccolo, Frieza Đại Đế, Cell Bọ Hung, Ma Buu...</p>\r\n<p>Dù đụng độ phải đối thủ mạnh hơn mình rất nhiều, Son Goku không hề nao núng, cậu luôn nỗ lực cải thiện sức mạnh của chính mình và coi kẻ thù giống như những thử thách thú vị cần vượt qua. Chính vì lí do đó mà xưa nay Son Goku vẫn luôn được độc giả xem như là biểu tượng của sự cố gắng không ngừng nghỉ.</p>\r\n<p>Suốt chặng đường trừ gian diệt ác ấy, Goku còn có những người thầy, người bạn sẵn sàng ở bên giúp đỡ, thậm chí vào sinh ra tử cùng cậu. Tác giả Toriyama Akira đã khẳng định một điều rằng: ta sẽ chẳng làm nên điều gì lớn lao nếu như ở bên không có những người bạn tốt. Triết lí: tình bạn – nỗ lực làm nên chiến thắng từ đó đã trở thành tôn chỉ của hầu hết những bộ truyện tranh thiếu niên sau này của Shonen Jump.</p>\r\n<p>Tuy Dragon Ball đã kết thúc nhưng sức hút của bộ truyện vẫn còn sôi sục cho tới tận ngày nay. Bên cạnh series 42 tập chính, Dragon Ball còn được tác giả Toriyama phát triển thành vũ trụ Dragon Ball thông qua các tác phẩm Anime, Movie, và mới đây là series Dragon Ball Super được NXB Kim Đồng mua bản quyền và phát hành gần như sát với Nhật Bản, mời quý vị độc giả đón đọc và ủng hộ.</p>', 'Nhà Xuất Bản Kim Đồng', 'Akira Toriyama', 16, 'Hành_động'),
(6, 'Dragon Ball Super - Tập 6 - Hỡi Các Siêu Chiến Binh, Hãy Tập Hợp!', 25000, 24000, 'images/product/dbs6_1.png', 'images/product/dbs6_2.png', 'images/product/dbs6_3.png', 'images/product/dbs6_4.png', 5, '<p>Dragon Ball Super Tập 6: Hỡi Các Siêu Chiến Binh, Hãy Tập Hợp! (Tái Bản 2022)</p>\r\n<p>Giải đấu sức mạnh do Đấng Toàn Năng làm “chủ xị” đã chính thức khởi tranh!! Vòng loại do các Thần Hủy Diệt tiến hành cũng đã xong, luật lệ cũng đã được ấn định: ngoại trừ vũ trụ chiến thắng, những vũ trụ thua cuộc đều sẽ bị hủy diệt. Goku đã phải khổ công chạy đôn chạy đáo để chọn ra 10 chiến binh xứng đáng nhất tham gia giải đấu như thế nào?</p>', 'Nhà Xuất Bản Kim Đồng', 'Akira Toriyama', 16, 'Hành_động'),
(7, 'One-Punch Man - Tập 1 - Chỉ Một Cú Đấm', 25000, 24000, 'images/product/opm1_1.png', 'images/product/opm1_2.png', 'images/product/opm1_3.png', 'images/product/opm1_4.png', 4, '<p>One-Punch Man - Tập 1: Chỉ Một Cú Đấm (Tái Bản 2022)</p>\r\n<p>Một đấm chết luôn! Người hùng Saitama quá mạnh, bất cứ ác nhân hay quái thú nào gặp anh cũng đều bị hạ gục dễ dàng chỉ sau một cú đấm! Truyền thuyết về người hùng lãnh đạm bắt đầu!!</p>', 'Nhà Xuất Bản Kim Đồng', 'One, Yusuke Murata', 16, 'Hành_động'),
(8, 'One-Punch Man - Tập 19 - Tận Diệt Cải Thảo', 25000, 24000, 'images/product/opm19_1.png', 'images/product/opm19_2.png', 'images/product/opm19_3.png', 'images/product/opm19_4.png', 4, '<p>Người bạn nhí Tareo của Garo đã bị Hiệp hội Quái nhân bắt sống. Trong lúc đó, tụi Genos lại đang hùng hục... ăn lẩu tại nhà của Saitama. Garo đơn thân tiến vào sào huyệt của đám Quái nhân, còn Hiệp hội Anh hùng thì sôi sục kế hoạch giải cứu cho cậu ấm hách dịch Waganma...</p>', 'Nhà Xuất Bản Kim Đồng', 'One, Yusuke Murata', 16, 'Hành_động'),
(9, 'Chainsaw Man - Tập 1 - Bìa 2 Mặt - Tặng Kèm Lót Ly Giấy + Standee PVC', 45000, 40000, 'images/product/csm1_1.png', 'images/product/csm1_2.png', 'images/product/csm1_3.png', 'images/product/csm1_4.png', 5, '<p>Chainsaw Man - Tập 1</p>\r\n<p>Quà Tặng:</p>\r\n<p>- Lót Ly Giấy, Bìa Giấy Kraft</p>\r\n<p>- Riêng Tập 1 Có Thêm Bìa 2 Mặt, Standee PVC</p>\r\n<p>Câu chuyện của CHAINSAW MAN mô tả một thế giới nơi ma quỷ và con người cùng tồn tại, và trong đó con người có thể lập khế ước để đạt được sức mạnh của quỷ.</p>\r\n<p>Vì số nợ khổng lồ của cha để lại, nhân vật chính Denji cùng con quỷ nhỏ Pochita làm tất cả mọi công việc để có thể hoàn nợ. Sau một tai nạn, Denji bị giết, Pochita đã hòa làm một với Denji, giúp cậu hồi sinh và hóa thành “Quỷ cưa” hùng mạnh. Sau đó, Denji được Makima nhận vào tổ chức săn quỷ và hành trình diệt quỷ của Denji bắt đầu từ đây.</p>', 'Trẻ', 'Tatsuki Fujimoto', 18, 'Hành_động'),
(10, 'Chainsaw Man - Tập 11 - Tặng Kèm Lót Ly + Card PVC', 50000, 45000, 'images/product/csm11_1.png', 'images/product/csm11_2.png', 'images/product/csm11_3.png', 'images/product/csm11_4.png', 5, '<p>Chainsaw Man - Tập 11</p>\r\n<p>Câu chuyện của Chainsaw Man mô tả một thế giới nơi ma quỷ và con người cùng tồn tại trên Trái đất, và trong đó con người có thể lập hiệp ước để đạt được sức mạnh của quỷ. </p>\r\n<p>Nhân vật chính là Denji, để hoàn trả số nợ khổng lồ của cha để lại, Denji cùng con quỷ nhỏ Pochita làm tất cả mọi công việc để có thể hoàn nợ. Sau một tai nạn, Denji bị giết, Pochita đã hòa làm một với Denji, giúp cậu hồi sinh và hóa thành “Quỷ cưa” hùng mạnh. Sau đó, Denji được Makima nhận vào tổ chức săn quỷ và hành trình diệt quỷ của Denji bắt đầu từ đây.</p>', 'Trẻ', 'Tatsuki Fujimoto', 18, 'Hành_động'),
(11, 'Re:zero - Bắt Đầu Lại Ở Thế Giới Khác - Phần 2 - Tập 5: Một Tuần Ở Dinh Thự', 50000, 45000, 'images/product/re25_1.png', 'images/product/re25_1.png', 'images/product/re25_1.png', 'images/product/re25_1.png', 5, '<p>Tập cuối cùng của Re:Zero phần 2 - Một tuần ở dinh thự. Subaru đã giải đáp được những bí ẩn xung quanh cái chết của mình. Cuối cùng cậu cũng có thể tận hưởng cuộc sống tươi đẹp tại dinh thự trước khi cuộc tuyển chọn quốc vương bắt đầu.</p>\r\n<p>Tập 5 bao gồm những chương truyện đặc biệt chưa từng xuất hiện trong bản light novel, do chính Tappei Nagatsuki sáng tác, hứa hẹn đem đến cho bạn đọc nhiều bất ngờ thú vị.</p>\r\n<p>Series manga RE: ZERO - BẮT ĐẦU LẠI Ở THẾ GIỚI KHÁC - PHẦN 2 MỘT TUẦN Ở DINH THỰ bao gồm 5 tập, là phần nối tiếp của RE: ZERO - BẮT ĐẦU LẠI Ở THẾ GIỚI KHÁC - PHẦN 1 MỘT NGÀY Ở VƯƠNG ĐÔ.</p>', 'IPM', 'Tappei Nagatsuki', 18, 'Hành_động'),
(12, 'Re:zero - Bắt Đầu Lại Ở Thế Giới Khác - Phần 2 - Tập 4: Một Tuần Ở Dinh Thự', 45000, 40000, 'images/product/re24_1.png', 'images/product/re24_1.png', 'images/product/re24_1.png', 'images/product/re24_1.png', 4, '<p>Với sự giúp đỡ của những người xung quanh, Subaru đã đánh bại “kẻ chủ mưu” sát hại mình trong vòng lặp đầu tiên, qua đó chấm dứt vòng lặp chết chóc và bước sang “buổi sáng hẹn ước”. Hãy đón đọc truyện tranh Re: Zero – Bắt đầu lại ở thế giới khác tập 4 để theo dõi đoạn kết của phần truyện “Một tuần ở dinh thự”.</p>', 'IPM', 'Tappei Nagatsuki', 18, 'Hành_động'),
(13, 'Fire Force - Tập 2 - Tặng Kèm Bookmark Giấy Hình Nhân Vật', 45000, 40000, 'images/product/ffc2_1.png', 'images/product/ffc2_2.png', 'images/product/ffc2_1.png', 'images/product/ffc2_2.png', 4, '<p>Fire Force - Tập 2</p>\r\n<p>Truyện lấy bối cảnh thế giới khi con người đối mặt với hiện tượng “nhân thể bộc hỏa”, tức con người tự bốc cháy. Câu chuyện nói về những con người có năng lực và quyết tâm kết hợp với nhau lập thành các Biệt đội cứu hỏa để bảo vệ con người trước “Diệm nhân”. Shinra Kusakabe là một chàng trai trẻ bị gắn biệt danh là “Dấu chân ác quỷ”, vì chân của cậu ấy có thể bốc cháy theo ý muốn. Sau khi cậu gia nhập Biệt đội cứu hỏa số 8, cậu đã cùng những đồng đội trong đội ngũ chiến đấu chống lại các Diệm nhân và theo đuổi lý tưởng anh hùng của mình. Trong hành trình bảo vệ nhân loại, Shinra dần phát hiện ra sự thật bất ngờ về nguyên nhân gây ra vụ hỏa hoạn dẫn tới cái chết đau đớn của gia đình cậu 12 năm về trước và quyết định cùng Biệt đội cứu hỏa số 8 tìm ra ngọn nguồn sự thật…</p>', 'Trẻ', 'Atsushi Ohkubo', 16, 'Hành_động'),
(14, 'Fire Force - Tập 27 - Tặng Kèm Bookmark Giấy Hình Nhân Vật', 45000, 40000, 'images/product/ffc27_1.png', 'images/product/ffc27_1.png', 'images/product/ffc27_1.png', 'images/product/ffc27_1.png', 4, '<p>Fire Force - Tập 27</p>\r\n<p>Truyện lấy bối cảnh thế giới khi con người đối mặt với hiện tượng “nhân thể bộc hỏa”, tức con người tự bốc cháy. Câu chuyện nói về những con người có năng lực và quyết tâm kết hợp với nhau lập thành các Biệt đội cứu hỏa để bảo vệ con người trước “Diệm nhân”. Shinra Kusakabe là một chàng trai trẻ bị gắn biệt danh là “Dấu chân ác quỷ”, vì chân của cậu ấy có thể bốc cháy theo ý muốn. Sau khi cậu gia nhập Biệt đội cứu hỏa số 8, cậu đã cùng những đồng đội trong đội ngũ chiến đấu chống lại các Diệm nhân và theo đuổi lý tưởng anh hùng của mình. Trong hành trình bảo vệ nhân loại, Shinra dần phát hiện ra sự thật bất ngờ về nguyên nhân gây ra vụ hỏa hoạn dẫn tới cái chết đau đớn của gia đình cậu 12 năm về trước và quyết định cùng Biệt đội cứu hỏa số 8 tìm ra ngọn nguồn sự thật…</p>', 'Trẻ', 'Atsushi Ohkubo', 16, 'Hành_động'),
(15, 'Sakamoto Days - Tập 1 - Sát Thủ Huyền Thoại - Bản Đặc Biệt - Tặng Kèm 1 Bìa Rời + 1 Obi + 6 Trang In Màu + 1 Pop-up Card + 1 Bookmark + 1 Set Sticker', 80000, 70000, 'images/product/skd1_1.png', 'images/product/skd1_2.png', 'images/product/skd1_3.png', 'images/product/skd1_4.png', 5, '<p>Sakamoto Days - Tập 1 - Sát Thủ Huyền Thoại</p>\r\n<p>Sakamoto Taro là sát thủ huyền thoại, vừa là nỗi khiếp sợ của các băng đảng tội phạm, vừa là niềm ước ao của các tay sát thủ. Nhưng một ngày nọ anh đã yêu, kết hôn và rửa tay gác kiếm.</p>\r\n<p>Từ một sát thủ khét tiếng, anh trở thành ông chú mũm mĩm, điều hành tiệm tạp hóa.</p>\r\n<p>Một ngày nọ, có cậu thanh niên đến tìm anh và ngỏ lời muốn anh tái xuất giang hồ nhưng anh đã từ chối. Kể từ đó nhiều nguy hiểm ập đến với anh và gia đình. Liệu anh có thể bảo vệ bản thân và gia đình của mình?</p>\r\n<p>Điểm nổi bật:</p>\r\n<p>- Đến tháng 1 năm 2024, manga đã có hơn 4.3 triệu bản in. Được đề cử cho Best Print Manga tại Lễ trao giải Next Manga Awards năm 2021.</p>\r\n<p>- Đứng thứ sáu trong danh sách những bộ truyện được nhân viên các nhà sách trên toàn quốc đề xuất nhiều nhất năm 2022.</p>\r\n<p>- Được đề cử và đứng hạng 6 trên tổng số 50 manga trong Shogakukan Manga Award lần thứ 68 ở hạng mục shonen vào năm 2022.</p>\r\n<p>- Thắng giåi U-Next Prize năm 2022.</p>', 'Trẻ', 'Yuto Suzuki', 18, 'Hành_động'),
(16, 'Sakamoto Days - Tập 4 - Trên Tàu Thì Phải Trật Tự', 45000, 40000, 'images/product/skd4_1.png', 'images/product/skd4_1.png', 'images/product/skd4_1.png', 'images/product/skd4_1.png', 4, '<p>Sakamoto Days - Tập 4 - Trên Tàu Thì Phải Trật Tự</p>\r\n<p>Sakamoto Taro là sát thủ huyền thoại, vừa là nỗi khiếp sợ của các băng đảng tội phạm, vừa là niềm ước ao của các tay sát thủ. Nhưng một ngày nọ anh đã yêu, kết hôn và rửa tay gác kiếm.</p>\r\n<p>Từ một sát thủ khét tiếng, anh trở thành ông chú mũm mĩm, điều hành tiệm tạp hóa.</p>\r\n<p>Một ngày nọ, có cậu thanh niên đến tìm anh và ngỏ lời muốn anh tái xuất giang hồ nhưng anh đã từ chối. Kể từ đó nhiều nguy hiểm ập đến với anh và gia đình. Liệu anh có thể bảo vệ bản thân và gia đình của mình?</p>\r\n<p>Điểm nổi bật:</p>\r\n<p>- Đến tháng 1 năm 2024, manga đã có hơn 4.3 triệu bản in. Được đề cử cho Best Print Manga tại Lễ trao giải Next Manga Awards năm 2021.</p>\r\n<p>- Đứng thứ sáu trong danh sách những bộ truyện được nhân viên các nhà sách trên toàn quốc đề xuất nhiều nhất năm 2022.</p>\r\n<p>- Được đề cử và đứng hạng 6 trên tổng số 50 manga trong Shogakukan Manga Award lần thứ 68 ở hạng mục shonen vào năm 2022.</p>\r\n<p>- Thắng giåi U-Next Prize năm 2022.</p>', 'Trẻ', 'Yuto Suzuki', 18, 'Hành_động'),
(17, 'One Piece - Tập 100 - Haki Bá Vương - Bản Bìa Áo', 25000, 24000, 'images/product/op100_1.png', 'images/product/op100_2.png', 'images/product/op100_3.png', 'images/product/op100_4.png', 4, '<p>Những nhân vật chủ chốt đều đã có mặt trên mái vòm, nhóm Luffy đối đầu với Kaido & Big Mom. Trước liên minh mạnh nhất thế giới, liệu có phép màu nào giúp bọn họ giành chiến thắng hay không!? Tương lai nào sẽ mở ra cho các chiến binh sau trận chiến cực hạn này!? Chỉ biết rằng đảo Quỷ vẫn không ngừng rung chuyển!!</p>\r\n<p>Những chuyến phiêu lưu trên đại dương xoay quanh “ONE PIECE” lại bắt đầu!!</p>\r\n<p>EIICHIRO ODA</p>\r\n<p>“Dường như trên mạng đã có lời đồn ác ý gì đó rồi. Nếu đằng ấy bị nói gì trên trường thì tui xin lỗi nha.”</p>\r\n<p>“Không sao đâu!!” - Thần hộ mệnh nhỏ nói.</p>\r\n<p>Thần hộ mệnh lớn thì bảo “Cứ vui lên!!” rồi bày ra cả mâm cơm thịnh soạn.</p>\r\n<p>“Mệt quá đi mất…” “Leo lên đây!!” chiếc xe khởi động chạy tới suối nước nóng!!</p>\r\n<p>“Tôi bị cảm rồi…” “Đấy mà là cảm hả!?” Đưa tới bệnh viện!! Nhập viện gấp!!</p>\r\n<p>Người đứng dưới ánh hào quang là tôi, nhưng khi đứng cạnh những người nổi tiếng thì đúng là có nhiều cảm xúc kém vui thiệt.</p>\r\n<p>Nếu thiếu đi những vị thần hộ mệnh vui vẻ ấy, thì tôi chắc chắn đã gục ngã mất!!</p>\r\n<p>Nhân dịp cột mốc 100 tập truyện được xác lập, có thể cho tôi mượn “khoảnh đất” này để gửi lời cảm ơn có được không!?</p>\r\n<p>XIN CẢM ƠN MỌI NGƯỜI SUỐT THỜI GIAN QUA!!</p>\r\n<p>Tập 100 rồi đấy!! Giờ thì hãy tiếp tục thưởng thức nhé!</p>\r\n', 'Nhà Xuất Bản Kim Đồng', 'Eiichiro Oda', 16, 'Phiêu_lưu'),
(18, 'One Piece - Tập 57 - Trận Chiến Thượng Đỉnh ', 25000, 24000, 'images/product/op57_1.png', 'images/product/op57_2.png', 'images/product/op57_3.png', 'images/product/op57_4.png', 4, '<p>One Piece Tập 57: Trận Chiến Thượng Đỉnh (Tái Bản 2022)</p>\r\n<p>Hải tặc mạnh nhất thế giới đã ra tay!! Để giải thoát cho Ace, binh đoàn của \"Râu Trắng\" đã lao vào trận chiến toàn diện với \"Hải quân\" và \"Vương hạ Thất Vũ hải\"!! Liệu Luffy có kịp góp mặt vào cuộc đối đầu thượng đỉnh làm rung chuyển cả thế giới này hay không...!?</p>\r\n<p>Những chuyến phiêu lưu trên đại dương xoay quanh \"ONE PIECE\" lại bắt đầu!!</p>', 'Nhà Xuất Bản Kim Đồng', 'Eiichiro Oda', 16, 'Phiêu_lưu'),
(19, 'Dragon Ball Super - Tập 20 - Lao Tâm Khổ Chiến - Tặng Kèm Postcard', 25000, 24000, 'images/product/dbs20_1.png', 'images/product/dbs20_2.png', 'images/product/dbs20_1.png', 'images/product/dbs20_2.png', 4, '<p>Dragon Ball Super - Tập 20: Lao Tâm Khổ Chiến</p>\r\n<p>Để đánh bại Gas, kẻ mạnh nhất vũ trụ lúc này, Goku và Vegeta buộc phải phát huy hết tiềm năng của “Bản năng vô cực” và “Bản ngã tối thượng” mà mỗi người đã lĩnh hội được. Giữa lúc nguy khốn đó, Granola đã trở lại, cuộc chiến sẽ ngã ngũ như thế nào đây... mời các bạn đón xem nhé!</p>\r\n<p>Bật mí chương sau: Trên Trái Đất bỗng xuất hiện bộ đôi siêu nhân gây xôn xao dư luận. Chính họ là người sẽ vén mèn giai đoạn tiếp theo của thế giới!!</p>', 'Nhà Xuất Bản Kim Đồng', 'Akira Toriyama', 11, 'Phiêu_lưu'),
(20, 'Dragon Ball Super - Tập 15 - Moro - Kẻ Ăn Hành Tinh', 25000, 24000, 'images/product/dbs15_1.png', 'images/product/dbs15_2.png', 'images/product/dbs15_3.png', 'images/product/dbs15_4.png', 4, '<p>Goku đã sử dụng Bản Năng Vô Cực để dồn Moro vào chân tường. Nhưng Moro lại lợi dụng kho dự trữ trong cánh tay trái bị cắt lìa của Merus để học được tuyệt chiêu này. Đối diện với sức mạnh của thần thánh, Goku sẽ xử trí thế nào?</p>\r\n<p>Toyotarou</p>\r\n<p>“Tranh vẽ của tôi được dựng thành mô hình nhựa rồi đó! Trong quá trình 3D hóa, tôi đã có một vài phát hiện lí thú và thu về khá nhiều kiến thức mới mẻ.”</p>', 'Nhà Xuất Bản Kim Đồng', 'Akira Toriyama', 16, 'Phiêu_lưu'),
(81, 'Thị Trấn Mèo - Tập 2', 70000, 60000, 'images/product/ttm2_1.png', 'images/product/ttm2_2.png', 'images/product/ttm2_3.png', 'images/product/ttm2_4.png', 4, '<p>Ở một làng chài nằm rìa Tokyo, luôn có hàng dài những chú mèo chiếm lĩnh mọi ngóc ngách của bến cảng, xếp hàng chờ ăn những con cá tươi ngon, béo ngậy vừa đánh bắt ngoài biển khơi về. Dần dần, chả biết chúng từ đâu cứ đến nơi đây, tạo thành khung cảnh có một không hai: một thị trấn đầy ắp những chú mèo trên mọi nẻo đường.</p>\r\n<p>Thị trấn mèo êm đềm nằm bên bờ biển, là ngôi nhà chung của các ông bà già cả và những chú mèo. Trong đó có ông lão Daikichi và chú mèo Tama vừa tròn 10 tuổi.</p>\r\n<p>Người và mèo ngày ngày quấn quýt, bầu bạn bên nhau, trải qua bốn mùa xuân - hạ - thu - đông, tới khi cùng bạc mái đầu.</p>\r\n<p>Sách có trang màu rực rỡ. Số tập 4+.</p>', 'Nhà Xuất Bản Kim Đồng', 'Nekomaki', 16, 'Đời_thường'),
(82, 'Combo Thị Trấn Mèo: Tập 1 Đến Tập 5', 340000, 300000, 'images/product/ttm6_1.png', 'images/product/ttm6_1.png', 'images/product/ttm6_1.png', 'images/product/ttm6_1.png', 4, '<p>Ở một làng chài nằm rìa Tokyo, luôn có hàng dài những chú mèo chiếm lĩnh mọi ngóc ngách của bến cảng, xếp hàng chờ ăn những con cá tươi ngon, béo ngậy vừa đánh bắt ngoài biển khơi về. Dần dần, chả biết chúng từ đâu cứ đến nơi đây, tạo thành khung cảnh có một không hai: một thị trấn đầy ắp những chú mèo trên mọi nẻo đường.</p>\r\n<p>Thị trấn mèo êm đềm nằm bên bờ biển, là ngôi nhà chung của các ông bà già cả và những chú mèo. Trong đó có ông lão Daikichi và chú mèo Tama vừa tròn 10 tuổi.</p>\r\n<p>Người và mèo ngày ngày quấn quýt, bầu bạn bên nhau, trải qua bốn mùa xuân - hạ - thu - đông, tới khi cùng bạc mái đầu.</p>\r\n<p>Sách có trang màu rực rỡ. Số tập 4+.</p>\r\n<p>Thị trấn mèo - Tập 1</p>\r\n<p>Thị trấn mèo - Tập 2</p>\r\n<p>Thị trấn mèo - Tập 3</p>\r\n<p>Thị trấn mèo - Tập 4</p>\r\n<p>Thị trấn mèo - Tập 5</p>', 'Nhà Xuất Bản Kim Đồng', 'Nekomaki', 16, 'Đời_thường');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`productID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
